lang: ru
debug: true
scoreboard:
  title: '&7&lTheTowers'
  lobby:
    lines:
      - '&0'
      - '&fПобед: &c%towers_wins%'
      - '&fПроигрышей: &c%towers_loses%'
      - '&1'
      - '&espigotmc.ru'
  in-game:
    lines:
      - '&0'
      - '&fЖизней: &c%health%❤'
      - '&fБаланс: &c%money%⏣'
      - '&1'
      - '&espigotmc.ru'
  waiting:
    lines:
      - '&0'
      - '&fОжидание'
      - '&fДо начала:'
      - '&f%time%'
      - '&1'
      - '&a%players%&6/&2%max_players%'
      - '&2'
      - '&espigotmc.ru'
world-name: 'world'
