#Башни
towers:
  #Лучник
  hunter:
    #Название
    title: '&7&lЛучник'
    #Описание
    desc:
      - '&0'
      - '&fСтреляет обычными стрелами'
      - '&fв злых мобов'
      - '&1'
    #Уровни
    levels:
      #Уровень A
      A:
        #Урон
        damage: 1
        #Цена
        cost: 15
        #Радиус атаки мобов
        radius: 4
        #Перезарядка снаряда (тики)
        recharge-time: 60
      B:
        #Урон
        damage: 1.5
        #Цена
        cost: 50
        #Радиус атаки мобов
        radius: 6
        #Перезарядка снаряда (тики)
        recharge-time: 50
      C:
        #Урон
        damage: 3
        #Цена
        cost: 120
        #Радиус атаки мобов
        radius: 10
        #Перезарядка снаряда (тики)
        recharge-time: 40
      D:
        #Урон
        damage: 4.5
        #Цена
        cost: 260
        #Радиус атаки мобов
        radius: 12
        #Перезарядка снаряда (тики)
        recharge-time: 30
      E:
        #Урон
        damage: 6
        #Цена
        cost: 550
        #Радиус атаки мобов
        radius: 15
        #Перезарядка снаряда (тики)
        recharge-time: 10
  #Замораживатель
  freezer:
    #Название
    title: '&b&lЗамораживатель'
    #Описание
    desc:
      - '&0'
      - '&fЗамораживает на определённое'
      - '&fвремя злых мобов'
      - '&1'
    #Уровни
    levels:
      #Уровень A
      A:
        #Заморозка (тики)
        time: 30
        #Цена
        cost: 40
        #Радиус атаки мобов
        radius: 3
        #Перезарядка снаряда (тики)
        recharge-time: 100
      B:
        #Заморозка (тики)
        time: 50
        #Цена
        cost: 125
        #Радиус атаки мобов
        radius: 4.5
        #Перезарядка снаряда (тики)
        recharge-time: 90
      C:
        #Заморозка (тики)
        time: 80
        #Цена
        cost: 240
        #Радиус атаки мобов
        radius: 5.5
        #Перезарядка снаряда (тики)
        recharge-time: 70
      D:
        #Заморозка (тики)
        time: 110
        #Цена
        cost: 370
        #Радиус атаки мобов
        radius: 8
        #Перезарядка снаряда (тики)
        recharge-time: 40
      E:
        #Заморозка (тики)
        time: 140
        #Цена
        cost: 750
        #Радиус атаки мобов
        radius: 13
        #Перезарядка снаряда (тики)
        recharge-time: 10
  #Огонёк
  fire:
    #Название
    title: '&c&lОгонёк'
    #Описание
    desc:
      - '&0'
      - '&fПоджигает на некоторое'
      - '&fвремя злых мобов'
      - '&1'
      - '&6Конфликс с &b&lЗамораживателем&6!'
      - '&6Мобы будут идти нормально!'
      - '&2'
    #Уровни
    levels:
      #Уровень A
      A:
        #Поджёг (тики)
        time: 20
        #Цена
        cost: 100
        #Радиус атаки мобов
        radius: 2
        #Перезарядка снаряда (тики)
        recharge-time: 140
      B:
        #Поджёг (тики)
        time: 30
        #Цена
        cost: 170
        #Радиус атаки мобов
        radius: 3.5
        #Перезарядка снаряда (тики)
        recharge-time: 130
      C:
        #Поджёг (тики)
        time: 60
        #Цена
        cost: 340
        #Радиус атаки мобов
        radius: 4
        #Перезарядка снаряда (тики)
        recharge-time: 90
      D:
        #Поджёг (тики)
        time: 90
        #Цена
        cost: 670
        #Радиус атаки мобов
        radius: 6.5
        #Перезарядка снаряда (тики)
        recharge-time: 60
      E:
        #Поджёг (тики)
        time: 140
        #Цена
        cost: 1000
        #Радиус атаки мобов
        radius: 8
        #Перезарядка снаряда (тики)
        recharge-time: 50
  #Помощник
  supporter:
    #Название
    title: '&d&lПомощник'
    #Описание
    desc:
      - '&0'
      - '&fУсиливает урон'
      - '&fсоюзных башен'
      - '&1'
    #Уровни
    levels:
      #Уровень A
      A:
        #Усиление (на ед.урона)
        gain: 2
        #Цена
        cost: 250
        #Радиус принятия башен
        radius: 2
      B:
        #Усиление (на ед.урона)
        gain: 5
        #Цена
        cost: 550
        #Радиус принятия башен
        radius: 4
      C:
        #Усиление (на ед.урона)
        gain: 7
        #Цена
        cost: 900
        #Радиус принятия башен
        radius: 7
      D:
        #Усиление (на ед.урона)
        gain: 12
        #Цена
        cost: 1700
        #Радиус принятия башен
        radius: 10
      E:
        #Усиление (на ед.урона)
        gain: 16
        #Цена
        cost: 2500
        #Радиус принятия башен
        radius: 19
  #Маячок
  beacon:
    #Название
    title: '&e&lМаячок'
    #Описание
    desc:
      - '&0'
      - '&fПодсвечивает невидимых мобов'
      - '&fдля союзных башен'
      - '&1'
    #Уровни
    levels:
      #Уровень A
      A:
        #Продолжительность подсветки
        time: 100
        #Цена
        cost: 450
      B:
        #Продолжительность подсветки
        time: 140
        #Цена
        cost: 1200
      C:
        #Продолжительность подсветки
        time: 260
        #Цена
        cost: 1800

troops:
  #Мертвяк
  zombie:
    #Название
    title: '&2Мертвяк'
    #Урон по замку
    damage: 1
    #Скорость передвижения (блок/сек)
    speed: 0.4
    #Цена
    cost: 10
    #Здоровье
    health: 0.5
    #Сколько выдаётся ⏣ за убийство
    killed: 3
  #Паудрон
  spider:
    #Название
    title: '&8Паудрон'
    #Урон по замку
    damage: 1.5
    #Скорость передвижения (блок/сек)
    speed: 0.5
    #Цена
    cost: 40
    #Здоровье
    health: 3
    #Сколько выдаётся ⏣ за убийство
    killed: 19
  #Тёща
  cave_spider:
    #Название
    title: '&1Тёща'
    #Урон по замку
    damage: 3
    #Скорость передвижения (блок/сек)
    speed: 0.1
    #Цена
    cost: 90
    #Здоровье
    health: 10
    #Сколько выдаётся ⏣ за убийство
    killed: 46
  #Училка
  creeper:
    #Название
    title: '&5Училка'
    #Урон по замку
    damage: 5
    #Скорость передвижения (блок/сек)
    speed: 0.2
    #Цена
    cost: 160
    #Здоровье
    health: 15
    #Сколько выдаётся ⏣ за убийство
    killed: 111
  #Предатор
  blaze:
    #Название
    title: '&6Предатор'
    #Урон по замку
    damage: 6.5
    #Скорость передвижения (блок/сек)
    speed: 0.7
    #Цена
    cost: 180
    #Здоровье
    health: 40
    #Сколько выдаётся ⏣ за убийство
    killed: 143
  #Летучая тварь (Инвизная)
  phantom:
    #Название
    title: '&9Летучая тварь &3(Невидимый)'
    #Урон по замку
    damage: 10
    #Скорость передвижения (блок/сек)
    speed: 1
    #Цена
    cost: 260
    #Здоровье
    health: 60
    #Сколько выдаётся ⏣ за убийство
    killed: 200
  #Желе
  slime:
    #Название
    title: '&aЖеле &3(Невидимый)'
    #Урон по замку
    damage: 12
    #Скорость передвижения (блок/сек)
    speed: 1.2
    #Цена
    cost: 350
    #Здоровье
    health: 100
    #Сколько выдаётся ⏣ за убийство
    killed: 287
